version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-tutorial"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l8dsrua6znb"
s3_prefix = "sam-tutorial"
region = "eu-west-1"
profile = "sam-tutorial"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"sam-tutorial\""
